name: env_zoo_calrissian
channels:
  - terradue
  - conda-forge
  - eoepca
dependencies:
  - python==3.10
  - black
  - pre-commit
  - isort
  - flake8
  - autoflake
  - pylint
  - nose2
  - git
  - pip
  - cwl-wrapper
  - loguru
  - pyyaml
  - kubernetes-client
  - kubernetes-node
  - kubernetes-server
  - pip:
    - git+https://github.com/UKEODHP/zoo-calrissian-runner.git@main
    - git+https://github.com/UKEODHP/pycalrissian.git@main
    - attrs
    - cwl-utils==0.14
    - kubernetes==28.1.0
    - cookiecutter
    - boto3
    - botocore
    - pystac
    - python-dotenv
    - pyjwt
